version: '3.8'
services:
  app:
      image: myproject:1.1.2
      ports:
        - "3000"  # Map port 3000 on host to port 3000 in container
      volumes:
        - ./app:/app  # Map the local 'app' directory to '/app' in the container
     
